apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  labels:
    app: "react-ui"
spec:
  selector:
    matchLabels:
      app: "react-ui"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "react-ui"
    spec:
      containers:
      - name: "react-ui"
        image: "hanifsuhail/ui:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "react-ui"
  name: "ui-service"
spec:
  selector:
    app: "react-ui"
  type: "NodePort"
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
