apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zuul-api-gateway"
  labels:
    app: "zuul-api-gateway"
spec:
  selector:
    matchLabels:
      app: "zuul-api-gateway"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "zuul-api-gateway"
    spec:
      containers:
      - name: "zuul-api-gateway"
        image: "hanifsuhail/zuul:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9999
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - react-ui
            topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "zuul-api-gateway"
  name: "zuul-api-gateway"
spec:
  selector:
    app: "zuul-api-gateway"
  type: NodePort
  ports:
  - name: "http"
    port: 9999
    targetPort: 9999
    nodePort: 32470
