apiVersion: apps/v1
kind: Deployment
metadata:
  name: "wishlist-ui"
  labels:
    app: "wishlist-ui"
spec:
  selector:
    matchLabels:
      app: "wishlist-ui"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "wishlist-ui"
    spec:
      containers:
      - name: "wishlist-ui"
        image: "hanifsuhail/wishlist:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "wishlist-ui"
  name: "wishlist"
spec:
  selector:
    app: "wishlist-ui"
  type: ClusterIP
  ports:
  - name: "http"
    port: 1003
    targetPort: 5000
