apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cart-ui"
  labels:
    app: "cart-ui"
spec:
  selector:
    matchLabels:
      app: "cart-ui"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "cart-ui"
    spec:
      containers:
      - name: "cart-ui"
        image: hanifsuhail/cart:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1004

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "cart-ui"
  name: "cart"
spec:
  selector:
    app: "cart-ui"
  type: ClusterIP
  ports:
  - name: "http"
    port: 1004
    targetPort: 1004
